return {
  "ta-tikoma/php.easy.nvim",
  config = true,
  keys = {
    { "-b", "<CMD>PHPEasyDocBlock<CR>" },
    { "-r", "<CMD>PHPEasyReplica<CR>" },
    { "-c", "<CMD>PHPEasyCopy<CR>" },
    { "-d", "<CMD>PHPEasyDelete<CR>" },
    { "-ii", "<CMD>PHPEasyInitInterface<CR>" },
    { "-ic", "<CMD>PHPEasyInitClass<CR>" },
    { "-iac", "<CMD>PHPEasyInitAbstractClass<CR>" },
    { "-it", "<CMD>PHPEasyInitTrait<CR>" },
    { "-ie", "<CMD>PHPEasyInitEnum<CR>" },
    { "-ic", "<CMD>PHPEasyAppendConstruct<CR>" },
    { "-ac", "<CMD>PHPEasyAppendConstant<CR>" },
    { "-ap", "<CMD>PHPEasyAppendProperty<CR>" },
    { "-am", "<CMD>PHPEasyAppendMethod<CR>" },
    { "-aa", "<CMD>PHPEasyAppendArgument<CR>" },
  },
}
